<?php

return [
    'solver' => [
        'default' => 'genetic',
        'population_size' => env('PLANNING_POPULATION_SIZE', 48),
        'generations' => env('PLANNING_GENERATIONS', 80),
        'elite_count' => env('PLANNING_ELITE_COUNT', 4),
        'crossover_rate' => env('PLANNING_CROSSOVER_RATE', 0.85),
        'mutation_rate' => env('PLANNING_MUTATION_RATE', 0.18),
        'repair_passes' => env('PLANNING_REPAIR_PASSES', 2),
        'time_limit_seconds' => env('PLANNING_TIME_LIMIT_SECONDS', 300),
        'stagnation_generations' => env('PLANNING_STAGNATION_GENERATIONS', 25),
    ],
    'weights' => [
        'unassigned_slot' => 100000,
        'missing_skill' => 100000,
        'senior_coverage_missing' => 100000,
        'absence_conflict' => 100000,
        'availability_conflict' => 100000,
        'holiday_conflict' => 100000,
        'overlap' => 100000,
        'min_rest_violation' => 50000,
        'daily_limit_exceeded' => 50000,
        'nominal_limit_exceeded' => 100000,
        'monthly_limit_exceeded' => 30000,
        'quarterly_limit_exceeded' => 30000,
        'even_hours' => 8000,
        'fallback_usage' => 1500,
        'contract_usage_per_hour' => 2000,
        'nominal_underfill_per_hour' => 8000,
        'nominal_overfill_per_hour' => 8000,
        'night_recovery_after_night' => 12000,
        'consecutive_nights' => 250000,
        'avoid_same_resource_streaks' => 80000,
        'spread_partial_top_ups' => 5000,
        'ward_manager_one_split_per_day' => 100000,
        'secondary_usage' => 300,
        'even_nights' => 3000,
        'even_weekends' => 500,
        'preference_mismatch' => 200,
    ],
    'rules' => [
        ['code' => 'unassigned_slot', 'name' => 'Nieobsadzone sloty', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'missing_skill', 'name' => 'Wymagane umiejętności', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'senior_coverage_missing', 'name' => 'Minimum jedna starsza w trójce', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'absence_conflict', 'name' => 'Absencje blokujące planowanie', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'availability_conflict', 'name' => 'Kalendarz dostępności zasobu', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'holiday_conflict', 'name' => 'Święta blokujące planowanie', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'overlap', 'name' => 'Brak nakładających się zmian', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'min_rest_violation', 'name' => 'Minimalny odpoczynek 11h', 'weight' => 50000, 'can_toggle' => false],
        ['code' => 'daily_limit_exceeded', 'name' => 'Limit dzienny', 'weight' => 50000, 'can_toggle' => false],
        ['code' => 'nominal_limit_exceeded', 'name' => 'Nie przekraczać nominału etatu', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'monthly_limit_exceeded', 'name' => 'Limit miesięczny', 'weight' => 30000, 'can_toggle' => false],
        ['code' => 'quarterly_limit_exceeded', 'name' => 'Limit kwartalny', 'weight' => 30000, 'can_toggle' => false],
        ['code' => 'even_hours', 'name' => 'Dążenie do nominału', 'weight' => 8000],
        ['code' => 'contract_usage', 'name' => 'Minimalizacja kontraktów/zleceń', 'weight' => 2000, 'metadata' => ['minimum_assignments_per_active_resource' => 1]],
        ['code' => 'night_recovery_after_night', 'name' => 'Po nocce preferuj pełny dzień wolny', 'weight' => 12000],
        ['code' => 'consecutive_nights', 'name' => 'Unikaj nocek pod rząd', 'weight' => 250000],
        ['code' => 'avoid_same_resource_streaks', 'name' => 'Unikaj serii tej samej osoby', 'weight' => 80000],
        ['code' => 'spread_partial_top_ups', 'name' => 'Rozciągaj dopełnienia po miesiącu', 'weight' => 5000, 'metadata' => ['minimum_employee_segment_minutes' => 360]],
        ['code' => 'ward_manager_one_split_per_day', 'name' => 'Oddziałowa maks. 1 podział dziennie', 'weight' => 100000, 'can_toggle' => false, 'metadata' => ['max_splits_per_day' => 1, 'max_prefixes_per_period' => 4, 'prefix_minutes' => 335, 'allowed_shift_codes' => ['DAY_12H']]],
        ['code' => 'fallback_usage', 'name' => 'Użycie fallback', 'weight' => 1500],
        ['code' => 'secondary_usage', 'name' => 'Użycie secondary', 'weight' => 300],
        ['code' => 'even_nights', 'name' => 'Bilans dniówek i nocek', 'weight' => 3000],
        ['code' => 'even_weekends', 'name' => 'Równomierny rozkład weekendów', 'weight' => 500],
    ],
];
