<?php

return [
    'solver' => [
        'default' => 'genetic',
        'population_size' => env('PLANNING_POPULATION_SIZE', 48),
        'generations' => env('PLANNING_GENERATIONS', 80),
        'elite_count' => env('PLANNING_ELITE_COUNT', 4),
        'crossover_rate' => env('PLANNING_CROSSOVER_RATE', 0.85),
        'mutation_rate' => env('PLANNING_MUTATION_RATE', 0.18),
        'repair_passes' => env('PLANNING_REPAIR_PASSES', 2),
        'time_limit_seconds' => env('PLANNING_TIME_LIMIT_SECONDS', 300),
        'stagnation_generations' => env('PLANNING_STAGNATION_GENERATIONS', 25),
    ],
    'weights' => [
        'unassigned_slot' => 100000,
        'missing_skill' => 100000,
        'senior_coverage_missing' => 100000,
        'absence_conflict' => 100000,
        'availability_conflict' => 100000,
        'holiday_conflict' => 100000,
        'overlap' => 100000,
        'min_rest_violation' => 50000,
        'daily_limit_exceeded' => 50000,
        'nominal_limit_exceeded' => 100000,
        'monthly_limit_exceeded' => 30000,
        'quarterly_limit_exceeded' => 30000,
        'even_hours' => 8000,
        'fallback_usage' => 1500,
        'contract_usage_per_hour' => 2000,
        'nominal_underfill_per_hour' => 8000,
        'nominal_overfill_per_hour' => 8000,
        'night_recovery_after_night' => 12000,
        'consecutive_nights' => 250000,
        'avoid_same_resource_streaks' => 80000,
        'spread_partial_top_ups' => 5000,
        'flex_resource_one_split_per_day' => 100000,
        'secondary_usage' => 300,
        'even_nights' => 3000,
        'even_weekends' => 500,
        'preference_mismatch' => 200,
    ],
    'rules' => [
        ['code' => 'unassigned_slot', 'name' => 'Nieobsadzone sloty', 'description' => 'Każde wymagane miejsce w grafiku powinno mieć przypisaną osobę.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'missing_skill', 'name' => 'Wymagane umiejętności', 'description' => 'Pracownik może trafić tylko tam, gdzie ma odpowiednie uprawnienia.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'senior_coverage_missing', 'name' => 'Minimum jedna starsza w trójce', 'description' => 'W każdej wymaganej grupie dyżurów musi być przynajmniej jedna starsza.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'absence_conflict', 'name' => 'Absencje blokujące planowanie', 'description' => 'Nie planuj pracy w czasie urlopu lub innej blokującej absencji.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'availability_conflict', 'name' => 'Kalendarz dostępności zasobu', 'description' => 'Uwzględnia stałe dni lub godziny, w których pracownik nie może pracować.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'holiday_conflict', 'name' => 'Święta blokujące planowanie', 'description' => 'Nie planuj pracy w dniach oznaczonych jako święta wyłączone z grafiku.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'overlap', 'name' => 'Brak nakładających się zmian', 'description' => 'Ta sama osoba nie może mieć dwóch zmian w tym samym czasie.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'min_rest_violation', 'name' => 'Minimalny odpoczynek 11h', 'description' => 'Między dyżurami musi zostać co najmniej 11h odpoczynku.', 'weight' => 50000, 'can_toggle' => false],
        ['code' => 'daily_limit_exceeded', 'name' => 'Limit dzienny', 'description' => 'Jedna osoba nie powinna mieć za dużo pracy w jednej dobie.', 'weight' => 50000, 'can_toggle' => false],
        ['code' => 'nominal_limit_exceeded', 'name' => 'Nie przekraczać nominału etatu', 'description' => 'Etatowiec nie może dostać więcej godzin niż pozwala jego limit.', 'weight' => 100000, 'can_toggle' => false],
        ['code' => 'monthly_limit_exceeded', 'name' => 'Limit miesięczny', 'description' => 'Pilnuje maksymalnej liczby godzin pracownika w miesiącu.', 'weight' => 30000, 'can_toggle' => false],
        ['code' => 'quarterly_limit_exceeded', 'name' => 'Limit kwartalny', 'description' => 'Pilnuje maksymalnej liczby godzin pracownika w kwartale.', 'weight' => 30000, 'can_toggle' => false],
        ['code' => 'even_hours', 'name' => 'Dążenie do nominału', 'description' => 'Stara się dopełnić etatowcom wymagane godziny z pracy i urlopów.', 'weight' => 8000],
        ['code' => 'contract_usage', 'name' => 'Minimalizacja kontraktów/zleceń', 'description' => 'Kontrakty i zlecenia są używane dopiero wtedy, gdy pomagają domknąć grafik.', 'weight' => 2000, 'metadata' => ['minimum_assignments_per_active_resource' => 1]],
        ['code' => 'night_recovery_after_night', 'name' => 'Po nocce preferuj pełny dzień wolny', 'description' => 'Po nocce najlepiej zostawić pracownikowi cały dzień wolny.', 'weight' => 12000],
        ['code' => 'consecutive_nights', 'name' => 'Unikaj nocek pod rząd', 'description' => 'Stara się nie dawać tej samej osobie kilku nocek z rzędu.', 'weight' => 250000],
        ['code' => 'avoid_same_resource_streaks', 'name' => 'Unikaj serii tej samej osoby', 'description' => 'Stara się nie układać wielu kolejnych dyżurów tej samej osobie.', 'weight' => 80000],
        ['code' => 'spread_partial_top_ups', 'name' => 'Rozciągaj dopełnienia po miesiącu', 'description' => 'Rozkłada krótsze dopełnienia równiej w całym miesiącu.', 'weight' => 5000, 'metadata' => ['minimum_employee_segment_minutes' => 360]],
        ['code' => 'flex_resource_one_split_per_day', 'name' => 'Zasób uzupełniający maks. 1 podział dziennie', 'description' => 'Zasób uzupełniający może domknąć najwyżej jedną zmianę w danym dniu.', 'weight' => 100000, 'can_toggle' => false, 'metadata' => ['max_splits_per_day' => 1, 'max_prefixes_per_period' => 4, 'prefix_minutes' => 335, 'allowed_shift_codes' => ['DAY_12H'], 'self_top_up_allowed_shift_codes' => ['DAY_12H'], 'self_top_up_allowed_unit_codes' => ['senior_ward']]],
        ['code' => 'fallback_usage', 'name' => 'Obsada rezerwowa', 'description' => 'Osoba rezerwowa może być użyta, ale dopiero gdy brakuje lepszej obsady.', 'weight' => 1500],
        ['code' => 'secondary_usage', 'name' => 'Obsada drugiego wyboru', 'description' => 'Osoba drugiego wyboru jest dopuszczalna, ale mniej preferowana niż podstawowa obsada.', 'weight' => 300],
        ['code' => 'even_nights', 'name' => 'Bilans dniówek i nocek', 'description' => 'Stara się równoważyć liczbę dniówek i nocek u jednej osoby.', 'weight' => 3000, 'metadata' => ['min_night_share_percent' => 25, 'max_night_share_percent' => 60, 'min_assignments_for_share' => 3]],
        ['code' => 'even_weekends', 'name' => 'Równomierny rozkład weekendów', 'description' => 'Stara się dzielić weekendy możliwie równo między pracowników.', 'weight' => 500],
    ],
];
